language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mwazovzky/docker-vue -f Dockerfile.dev .

script:
  - docker run -e CI=true mwazovzky/docker-vue npm run test:unit